[package]
name = "getvideo"
version = "0.1.0"
edition = "2024"
default-run = "client"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
dialoguer = "0.11.0"
log = "0.4.22"
xml = "0.8.20"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.38"
env_logger = "0.11.5"
anyhow = "1.0.86"
xmtv_api = "0.2.2"
rupnp = "2.0"
socket2 = "0.5"
if-addrs = "0.15"
futures = "0.3"

[lib]
name = "getvideo"
path = "src/lib.rs"

[[example]]
name = "mock_renderer"
path = "examples/mock_renderer.rs"

[[bin]]
name = "client"
path = "src/main.rs"

[[bin]]
name = "auto"
path = "src/auto_main.rs"

[[example]]
name = "scan"
path = "examples/scan.rs"
